#ifndef PROTO_AML_H
#define PROTO_AML_H

/*
**	$VER: aml.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_AML_PRAGMAS_H
#include <pragmas/aml_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * AmlBase;

#endif /* PROTO_AML_H */
