#ifndef PROTO_BATTCLOCK_H
#define PROTO_BATTCLOCK_H

/*
**	$VER: battclock.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_BATTCLOCK_PRAGMAS_H
#include <pragmas/battclock_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * BattClockBase;

#endif /* PROTO_BATTCLOCK_H */
