#ifndef PROTO_BEVEL_H
#define PROTO_BEVEL_H

/*
**	$VER: bevel.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_BEVEL_PRAGMAS_H
#include <pragmas/bevel_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * BevelBase;

#endif /* PROTO_BEVEL_H */
