#ifndef PROTO_BULLET_H
#define PROTO_BULLET_H

/*
**	$VER: bullet.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_BULLET_PRAGMAS_H
#include <pragmas/bullet_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * BulletBase;

#endif /* PROTO_BULLET_H */
