#ifndef PROTO_CARDRES_H
#define PROTO_CARDRES_H

/*
**	$VER: cardres.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_CARDRES_PRAGMAS_H
#include <pragmas/cardres_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * CardResource;

#endif /* PROTO_CARDRES_H */
