#ifndef PROTO_CHOOSER_H
#define PROTO_CHOOSER_H

/*
**	$VER: chooser.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_CHOOSER_PRAGMAS_H
#include <pragmas/chooser_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * ChooserBase;

#endif /* PROTO_CHOOSER_H */
