#ifndef PROTO_CLICKTAB_H
#define PROTO_CLICKTAB_H

/*
**	$VER: clicktab.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_CLICKTAB_PRAGMAS_H
#include <pragmas/clicktab_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * ClickTabBase;

#endif /* PROTO_CLICKTAB_H */
