#ifndef PROTO_COMMODITIES_H
#define PROTO_COMMODITIES_H

/*
**	$VER: commodities.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_COMMODITIES_PRAGMAS_H
#include <pragmas/commodities_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * CxBase;

#endif /* PROTO_COMMODITIES_H */
