#ifndef PROTO_CONSOLE_H
#define PROTO_CONSOLE_H

/*
**	$VER: console.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_CONSOLE_PRAGMAS_H
#include <pragmas/console_pragmas.h>
#endif

#ifndef EXEC_DEVICES_H
#include <exec/devices.h>
#endif

extern struct Device * ConsoleDevice;

#endif /* PROTO_CONSOLE_H */
