#ifndef PROTO_DATATYPES_H
#define PROTO_DATATYPES_H

/*
**	$VER: datatypes.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_DATATYPES_PRAGMAS_H
#include <pragmas/datatypes_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * DataTypesBase;

#endif /* PROTO_DATATYPES_H */
