#ifndef PROTO_DISKFONT_H
#define PROTO_DISKFONT_H

/*
**	$VER: diskfont.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_DISKFONT_PRAGMAS_H
#include <pragmas/diskfont_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * DiskfontBase;

#endif /* PROTO_DISKFONT_H */
