#ifndef PROTO_DRAWLIST_H
#define PROTO_DRAWLIST_H

/*
**	$VER: drawlist.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_DRAWLIST_PRAGMAS_H
#include <pragmas/drawlist_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * DrawListBase;

#endif /* PROTO_DRAWLIST_H */
