#ifndef PROTO_DTCLASS_H
#define PROTO_DTCLASS_H

/*
**	$VER: dtclass.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_DTCLASS_PRAGMAS_H
#include <pragmas/dtclass_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * DTClassBase;

#endif /* PROTO_DTCLASS_H */
