#ifndef PROTO_EXEC_H
#define PROTO_EXEC_H

/*
**	$VER: exec.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_EXEC_PRAGMAS_H
#include <pragmas/exec_sysbase_pragmas.h>
#endif

#ifndef EXEC_EXECBASE_H
#include <exec/execbase.h>
#endif

extern struct ExecBase * SysBase;

#endif /* PROTO_EXEC_H */
