#ifndef PROTO_FUELGAUGE_H
#define PROTO_FUELGAUGE_H

/*
**	$VER: fuelgauge.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_FUELGAUGE_PRAGMAS_H
#include <pragmas/fuelgauge_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * FuelGaugeBase;

#endif /* PROTO_FUELGAUGE_H */
