#ifndef PROTO_GADTOOLS_H
#define PROTO_GADTOOLS_H

/*
**	$VER: gadtools.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_GADTOOLS_PRAGMAS_H
#include <pragmas/gadtools_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * GadToolsBase;

#endif /* PROTO_GADTOOLS_H */
