#ifndef PROTO_GETFILE_H
#define PROTO_GETFILE_H

/*
**	$VER: getfile.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_GETFILE_PRAGMAS_H
#include <pragmas/getfile_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * GetFileBase;

#endif /* PROTO_GETFILE_H */
