#ifndef PROTO_GRAPHICS_H
#define PROTO_GRAPHICS_H

/*
**	$VER: graphics.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_GRAPHICS_PRAGMAS_H
#include <pragmas/graphics_pragmas.h>
#endif

#ifndef GRAPHICS_GFXBASE_H
#include <graphics/gfxbase.h>
#endif

extern struct GfxBase * GfxBase;

#endif /* PROTO_GRAPHICS_H */
