#ifndef PROTO_HDWRENCH_H
#define PROTO_HDWRENCH_H

/*
**	$VER: hdwrench.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_HDWRENCH_PRAGMAS_H
#include <pragmas/hdwrench_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * HDWBase;

#endif /* PROTO_HDWRENCH_H */
