#ifndef PROTO_IFFPARSE_H
#define PROTO_IFFPARSE_H

/*
**	$VER: iffparse.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_IFFPARSE_PRAGMAS_H
#include <pragmas/iffparse_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * IFFParseBase;

#endif /* PROTO_IFFPARSE_H */
