#ifndef PROTO_INPUT_H
#define PROTO_INPUT_H

/*
**	$VER: input.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_INPUT_PRAGMAS_H
#include <pragmas/input_pragmas.h>
#endif

#ifndef EXEC_DEVICES_H
#include <exec/devices.h>
#endif

extern struct Device * InputBase;

#endif /* PROTO_INPUT_H */
