#ifndef PROTO_INTUITION_H
#define PROTO_INTUITION_H

/*
**	$VER: intuition.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_INTUITION_PRAGMAS_H
#include <pragmas/intuition_pragmas.h>
#endif

#ifndef INTUITION_INTUITIONBASE_H
#include <intuition/intuitionbase.h>
#endif

extern struct IntuitionBase * IntuitionBase;

#endif /* PROTO_INTUITION_H */
