#ifndef PROTO_KEYMAP_H
#define PROTO_KEYMAP_H

/*
**	$VER: keymap.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_KEYMAP_PRAGMAS_H
#include <pragmas/keymap_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * KeymapBase;

#endif /* PROTO_KEYMAP_H */
