#ifndef PROTO_LAYERS_H
#define PROTO_LAYERS_H

/*
**	$VER: layers.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_LAYERS_PRAGMAS_H
#include <pragmas/layers_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * LayersBase;

#endif /* PROTO_LAYERS_H */
