#ifndef PROTO_LAYOUT_H
#define PROTO_LAYOUT_H

/*
**	$VER: layout.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_LAYOUT_PRAGMAS_H
#include <pragmas/layout_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * LayoutBase;

#endif /* PROTO_LAYOUT_H */
