#ifndef PROTO_LOCALE_H
#define PROTO_LOCALE_H

/*
**	$VER: locale.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_LOCALE_PRAGMAS_H
#include <pragmas/locale_pragmas.h>
#endif

#ifndef LIBRARIES_LOCALE_H
#include <libraries/locale.h>
#endif

extern struct LocaleBase * LocaleBase;

#endif /* PROTO_LOCALE_H */
