#ifndef PROTO_LOWLEVEL_H
#define PROTO_LOWLEVEL_H

/*
**	$VER: lowlevel.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_LOWLEVEL_PRAGMAS_H
#include <pragmas/lowlevel_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * LowLevelBase;

#endif /* PROTO_LOWLEVEL_H */
