#ifndef PROTO_MATHIEEESINGBAS_H
#define PROTO_MATHIEEESINGBAS_H

/*
**	$VER: mathieeesingbas.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_MATHIEEESINGBAS_PRAGMAS_H
#include <pragmas/mathieeesingbas_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * MathIeeeSingBasBase;

#endif /* PROTO_MATHIEEESINGBAS_H */
