#ifndef PROTO_MATHTRANS_H
#define PROTO_MATHTRANS_H

/*
**	$VER: mathtrans.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_MATHTRANS_PRAGMAS_H
#include <pragmas/mathtrans_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * MathTransBase;

#endif /* PROTO_MATHTRANS_H */
