#ifndef PROTO_MATHIEEEDOUBTRANS_H
#define PROTO_MATHIEEEDOUBTRANS_H

/*
**	$VER: mathieeedoubtrans.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_MATHIEEEDOUBTRANS_PRAGMAS_H
#include <pragmas/mathieeedoubtrans_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * MathIeeeDoubTransBase;

#endif /* PROTO_MATHIEEEDOUBTRANS_H */
