#ifndef PROTO_MATHFFP_H
#define PROTO_MATHFFP_H

/*
**	$VER: mathffp.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_MATHFFP_PRAGMAS_H
#include <pragmas/mathffp_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * MathBase;

#endif /* PROTO_MATHFFP_H */
