#ifndef PROTO_MATHIEEEDOUBBAS_H
#define PROTO_MATHIEEEDOUBBAS_H

/*
**	$VER: mathieeedoubbas.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_MATHIEEEDOUBBAS_PRAGMAS_H
#include <pragmas/mathieeedoubbas_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * MathIeeeDoubBasBase;

#endif /* PROTO_MATHIEEEDOUBBAS_H */
