#ifndef PROTO_MATHIEEESINGTRANS_H
#define PROTO_MATHIEEESINGTRANS_H

/*
**	$VER: mathieeesingtrans.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_MATHIEEESINGTRANS_PRAGMAS_H
#include <pragmas/mathieeesingtrans_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * MathIeeeSingTransBase;

#endif /* PROTO_MATHIEEESINGTRANS_H */
