#ifndef PROTO_MISC_H
#define PROTO_MISC_H

/*
**	$VER: misc.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_MISC_PRAGMAS_H
#include <pragmas/misc_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * MiscBase;

#endif /* PROTO_MISC_H */
