#ifndef PROTO_PENMAP_H
#define PROTO_PENMAP_H

/*
**	$VER: penmap.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_PENMAP_PRAGMAS_H
#include <pragmas/penmap_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * PenMapBase;

#endif /* PROTO_PENMAP_H */
