#ifndef PROTO_POPCYCLE_H
#define PROTO_POPCYCLE_H

/*
**	$VER: popcycle.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_POPCYCLE_PRAGMAS_H
#include <pragmas/popcycle_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * PopCycleBase;

#endif /* PROTO_POPCYCLE_H */
