#ifndef PROTO_POTGO_H
#define PROTO_POTGO_H

/*
**	$VER: potgo.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_POTGO_PRAGMAS_H
#include <pragmas/potgo_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * PotgoBase;

#endif /* PROTO_POTGO_H */
