#ifndef PROTO_RADIOBUTTON_H
#define PROTO_RADIOBUTTON_H

/*
**	$VER: radiobutton.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_RADIOBUTTON_PRAGMAS_H
#include <pragmas/radiobutton_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * RadioButtonBase;

#endif /* PROTO_RADIOBUTTON_H */
