#ifndef PROTO_REALTIME_H
#define PROTO_REALTIME_H

/*
**	$VER: realtime.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_REALTIME_PRAGMAS_H
#include <pragmas/realtime_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * RealTimeBase;

#endif /* PROTO_REALTIME_H */
