#ifndef PROTO_REQUESTER_H
#define PROTO_REQUESTER_H

/*
**	$VER: requester.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_REQUESTER_PRAGMAS_H
#include <pragmas/requester_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * RequesterBase;

#endif /* PROTO_REQUESTER_H */
