#ifndef PROTO_REXXSYSLIB_H
#define PROTO_REXXSYSLIB_H

/*
**	$VER: rexxsyslib.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_REXXSYSLIB_PRAGMAS_H
#include <pragmas/rexxsyslib_pragmas.h>
#endif

#ifndef REXX_RXSLIB_H
#include <rexx/rxslib.h>
#endif

extern struct RxsLib * RexxSysBase;

#endif /* PROTO_REXXSYSLIB_H */
