#ifndef PROTO_SLIDER_H
#define PROTO_SLIDER_H

/*
**	$VER: slider.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_SLIDER_PRAGMAS_H
#include <pragmas/slider_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * SliderBase;

#endif /* PROTO_SLIDER_H */
