#ifndef PROTO_SPACE_H
#define PROTO_SPACE_H

/*
**	$VER: space.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_SPACE_PRAGMAS_H
#include <pragmas/space_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * SpaceBase;

#endif /* PROTO_SPACE_H */
