#ifndef PROTO_SPEEDBAR_H
#define PROTO_SPEEDBAR_H

/*
**	$VER: speedbar.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_SPEEDBAR_PRAGMAS_H
#include <pragmas/speedbar_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * SpeedBarBase;

#endif /* PROTO_SPEEDBAR_H */
