#ifndef PROTO_STRING_H
#define PROTO_STRING_H

/*
**	$VER: string.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_STRING_PRAGMAS_H
#include <pragmas/string_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * StringBase;

#endif /* PROTO_STRING_H */
