#ifndef PROTO_TEXTEDITOR_H
#define PROTO_TEXTEDITOR_H

/*
**	$VER: texteditor.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_TEXTEDITOR_PRAGMAS_H
#include <pragmas/texteditor_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * TextEditorBase;

#endif /* PROTO_TEXTEDITOR_H */
