#ifndef PROTO_TEXTFIELD_H
#define PROTO_TEXTFIELD_H

/*
**	$VER: textfield.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_TEXTFIELD_PRAGMAS_H
#include <pragmas/textfield_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * TextFieldBase;

#endif /* PROTO_TEXTFIELD_H */
