#ifndef PROTO_TRANSLATOR_H
#define PROTO_TRANSLATOR_H

/*
**	$VER: translator.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_TRANSLATOR_PRAGMAS_H
#include <pragmas/translator_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * TranslatorBase;

#endif /* PROTO_TRANSLATOR_H */
