#ifndef PROTO_WB_H
#define PROTO_WB_H

/*
**	$VER: wb.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_WB_PRAGMAS_H
#include <pragmas/wb_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * WorkbenchBase;

#endif /* PROTO_WB_H */
