#ifndef PROTO_WINDOW_H
#define PROTO_WINDOW_H

/*
**	$VER: window.h 44.1 (1.11.1999)
**	Includes Release 44.1
**
**	Lattice `C' style prototype/pragma header file combo
**
**	(C) Copyright 1999 Amiga, Inc.
**	    All Rights Reserved
*/

#ifndef PRAGMAS_WINDOW_PRAGMAS_H
#include <pragmas/window_pragmas.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

extern struct Library * WindowBase;

#endif /* PROTO_WINDOW_H */
